# Generated by Django 2.1.5 on 2019-02-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Bathrooms',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Bedrooms',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Garage',
            new_name='garage',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Zipcode',
            new_name='zipcode',
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
